config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users, controllers: { registrations: "registrations" }
#   resource :accounts

#   ### Changes Start Here ###
#   get 'user/me', to: 'users#me', as: 'my_settings'
#   patch 'user/update_me', to: 'users#update_me', as: 'update_my_settings'
#   get 'user/password', to: 'users#password', as: 'my_password'
#   patch 'user/update_password', to: 'users#update_password', as: 'my_update_password'
#   scope 'account', as: 'account' do
#     resources :users
#   end
#   ### Changes End Here ###

#   get 'activity/mine'
#   get 'activity/feed'

#   root to: 'activity#mine'
# end




Rails.application.routes.draw do
  get 'user/index'
  get 'user/show'
  get 'user/new'
  get 'user/create'
  get 'user/edit'
  get 'user/update'
  devise_for :users,controllers: {registrations: "registrations"}
  resource :accounts

  get 'user/me', to: 'users#me', as: 'my_settings'
  patch 'user/update_me', to: 'users#update_me', as: 'upload_my_settings'
  get 'user/password', to: 'users#password', as: 'my_password'
  patch 'user/update_password', to: 'users#update_password', as: 'my_update_password'

  scope 'account', as: 'account' do
    resources :users
  end

  get 'activity/mine'
  get 'activity/feed'

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'activity#mine'
end

app/models/account.rb
class Account < ApplicationRecord
	resourcify
	has_many :users
	validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  self.implicit_order_column = "created_at"
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  belongs_to :account, optional: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    redirect_to root_path unless current_user.account.nil?
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      current_user.account = @account
      current_user.add_role :admin, @account
      current_user.save
      redirect_to root_path, success: "Your account has been created!"
    else
      render :new
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :addr1, :addr2, :city, :state, :zip, :country)
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def mine
  end

  def feed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :authenticate_user!
	layout :layout_by_resource

	# helper method
	helper_method :current_account

	def current_account
		@current_account ||= current_user.account
		@current_account
	end

	protected
	def layout_by_resource
		if devise_controller?
			"devise"
		else
			"application"
		end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_up_path_for(resource)
    new_accounts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:index]

  def index
    @users = current_account
  end

  def new
    @user = User.new
    set_choices
  end

  def edit
    set_choices
  end

  def me
    @user = current_user
  end

  def password
    @user = current_user
  end

  def update_password
    @user = current_user
    respond_to do |format|
      if @user.update(user_password_params)
        bypass_sign_in(@user)
        format.html {
          redirect_to my_password_path,
          notice: 'Password was successfully updated.'
        }
      else
        format.html { render :password }
      end
    end
  end

  def update_me
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html {
          redirect_to my_settings_path,
          notice: 'Your information was successfully updated.'
        }
      else
        format.html { render :me }
      end
    end
  end

  def create
    @user = User.unscoped.new(user_params.except("role"))
    @user.account = current_account
    @user.password = "password123"
    respond_to do |format|
      begin
        if @user.valid? && @user.invite!(current_user)
          @user.add_role user_params[:role].to_sym, current_account
          format.html {
            redirect_to account_users_path,
            notice: 'User was successfully invited.'
          }
        else
          set_choices
          format.html { render :new }
        end
      rescue ActiveRecord::RecordNotUnique
        flash[:alert] = 'Email must be unique'
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params.except('role'))
        update_roles
        format.html {
          redirect_to account_users_path,
          notice: 'User was successfully updated.'
        }
      else
        set_choices
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html {
        redirect_to account_users_path,
        notice: 'User was successfully destroyed.'
      }
      format.json { head :no_content }
    end
  end

  private

  def set_users
    if current_account
      @users = current_account.users
    else
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_choices
    @choices = [["Admin", 'admin'],["User", 'user']]
  end

  def user_params
    params.require(:user).permit(:name, :email, :role, :time_zone)
  end

  def user_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def update_roles
    if @user.roles&.first&.name != user_params[:role]
      @user.remove_role @user.roles&.first&.name.to_sym
      @user.add_role user_params[:role].to_sym, current_account
    end
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tailwind_color_class_for(flash_type)
    {
      success: "green",
      error: "red",
      alert: "orange",
      notice: "yellow"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    # return if flash[0][0] == :form_error
    flash.each do |msg_type, message|
      next if msg_type == :form_error
      concat(content_tag(:div, message.html_safe, {
        class: "alert transition-all duration-1000 ease-in-out p-4 m-4 mt-5 w-3/5 bg-{tailwind_color_class_for(msg_type)}-100 border border-{tailwind_color_class_for(msg_type)}-400 text-{tailwind_color_class_for(msg_type)}-700 rounded-lg",
        role: msg_type
      }) do
        concat content_tag(:span, message.html_safe, { class: "block sm:inline" })
      end)
    end
    nil
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/activity/feed.html.erb
<div>
  <h1 class="font-bold text-4xl">Activity#feed</h1>
  <p>Find me in app/views/activity/feed.html.erb</p>
</div>

app/views/activity/mine.html.erb
<div>
  <h1 class="font-bold text-4xl">Activity#mine</h1>
  <p>Find me in app/views/activity/mine.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StandupApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body class="bg-gray-800 font-sans leading-normal tracking-normal mt-12">
  <%= render partial: 'layouts/components/header' %>
  <div class="flex flex-col md:flex-row">

    <%= render partial: 'layouts/components/sidebar' %>
    <div class="main-content flex-1 bg-gray-100 mt-12 md:mt-2 pb-24 md:pb-5">
      <div class="flex items-center justify-center">
        <%= flash_messages %>
      </div>
      <div class="flex flex-wrap p-3">
        <%= yield %>
      </div>
      <%= render partial: 'layouts/components/footer' %>
    </div>
  </div>
</body>
</html>

app/views/layouts/components/_footer.html.erb
<footer class="w-full fixed bottom-0 p-1 pl-16 bg-gray-30 0 text-gray-600">
  © 2024 Copyright: standup App 
</footer>

app/views/layouts/components/_header.html.erb
<header>
  <nav aria-label="menu nav" class="bg-gray-800 pt-2 md:pt-1 pb-1 px-1 mt-0 h-auto fixed w-full z-20 top-0">
    <div class="flex flex-wrap items-center">
      <div class="flex flex-shrink md:w-1/3 justify-center md:justify-start text-white">
        <a href="#" aria-label="Home">
          <span class="text-xl pl-2">Logo</span>
        </a>
    </div>
    <div class="flex flex-1 md:w-1/3 justify-center md:justify-start text-white px-2">
      <span class="relative w-full">
        <input aria-label="search" type="search" id="search" placeholder="Search" class="w-full bg-gray-900 text-white transition border border-transparent focus:outline-none focus:border-gray-400 rounded py-3 px-2 pl-10 appearance-none leading-normal">
        <div class="absolute search-icon" style="top: 1rem; left: .8rem;">
          <svg class="fill-current pointer-events-none text-white w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
            </svg>
        </div>
      </span>
    </div>
    <div class="flex w-full pt-2 content-center justify-between md:w-1/3 md:justify-end">
      <ul class="list-reset flex justify-between flex-1md:flex-none items-center">
        <li class="flex-1 md:flex-none md:mr-3">
          <a class="inline-block py-2 px-4 text-white no-underline" href="#">Active</a>
          </li>
          <li class="flex-1 md:flex-none md:mr-3">
            <a class="inline-block text-gray-400 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" href="#">link</a>
          </li>
          <li class="flex-1 md:flex-none md:mr-3">
            <div data-controller="dropdown" class="relative inline-block">
              <button data-action="dropdown#toggle click@window->dropdown#hide" class="drop-button text-white py-2 px-2">
                <span class="pr-2"></span> Hi, User <svg class="h-3 fill-current inline" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" /></svg>
              </button>
              <div data-dropdown-target="menu" class="hidden absolute bg-gray-800 text-white right-0 mt-3 p-3 overflow-auto z-30" data-transition-enter-from="opacity-0 scale-95" data-transition-enter-to="opacity-100 scale-100" data-transition-leave-from="opacity-100 scale-100" data-transition-leave-to="opacity-0 scale-95" id="nav-dropdown">
                <a href="#" data-action="dropdown#toggle" class="p-2 hover:bg-gray-800 text-white text-sm no-underline hover:no-underline block"><i class="fa fa-user fa-fw"></i>
                  Profile
                </a>
                <a href="#" data-action="dropdown#toggle" class="p-2 hover:bg-gray-800 text-white text-sm no-underline hover:no-underline block"><i class="fa fa-cog fa-fw"></i>
                   Settings
                 </a>
                <div class="border border-gray-800"></div>
                <a href="#" data-action="dropdown#toggle" class="p-2 hover:bg-gray-800 text-white text-sm no-underline hover:no-underline block">
                  <i class="fas fa-sign-out-alt fa-fw"></i>
                  Log Out
                </a>
              </div>
            </div>
          </li>
      </ul>
    </div>
  </div>
  </nav>
</header>

app/views/layouts/components/_sidebar.html.erb
<div class="bg-gray-800 shadow-xl h-16 fixed bottom-0 mt-12 md:relative md:h-screen z-10 w-full md:w-48">
  <div class="md:mt-12 md:w-48 md:fixed md:left-0 md:top-0 content-center md:content-start text-left justify-between">
    <ul class="list-reset flex flex-row md:flex-col py-0 md:py-3 px-1 md:px-2 text-center md:text-left">
      <li class="mr-3 flex-1">
        <a href="#" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-pink-500">
          <i class="fas fa-tasks pr-0 md:pr-3"></i>
          <span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">Tasks</span>
        </a> 
      </li>
      <li class="mr-3 flex-1">
        <a href="#" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-purple-500">
          <i class="fa fa-envelope pr-0 md:pr-3"></i>
          <span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">
            Messages
          </span>
        </a> 
      </li>
      <li class="mr-3 flex-1">
        <a href="#" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-blue-600">
          <i class="fas fa-chart-area pr-0 md:pr-3 text-blue-600"></i>
          <span class="pb-1 md:pb-0 text-xs md:text-base text-white md:text-white block md:inline-block">Analytics</span>
        </a> 
      </li>
      <li class="mr-3 flex-1">
        <a href="#" class="block py-1 md:py-3 pl-0 md:pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-red-500">
          <i class="fa fa-wallet pr-0 md:pr-3"></i>
          <span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">
            Payments
          </span>
        </a> 
      </li>
    </ul>
 </div>
</div>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
  <html class="h-full">
    <head>
    <title>StandupApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
   </head>
    <body class="bg-gray-100 h-full">
      <div class="flex items-center justify-center">
        <%= flash_messages %>
      </div>
      <div class="min-h-full flex items-center justify-center">
        <div class="bg-neutral-50 shadow-md rounded-sm border m-auto min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
          <div class="max-w-md w-full space-y-8">
            <%= yield %> 
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">User#create</h1>
  <p>Find me in app/views/user/create.html.erb</p>
</div>

app/views/users/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">User#edit</h1>
  <p>Find me in app/views/user/edit.html.erb</p>
</div>

app/views/users/index.html.erb
<div class="flex p-5" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-3">
    <li class="inline-flex items-center">
      <h2 href="#" class="inline-flex items-center font-medium text-gray-700 hover:text-gray-900">
        Users
      </h2>
    </li>
  </ol>
</div>

<div class="flex justify-center">
  <div class="p-4 w-4/5 bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 lg:p-8">
    <h5 class="text-xl font-bold leading-none text-gray-900">
      <%= "Users in {current_account.name}" %>
    </h5>
    <table class="w-full text-sm text-left text-gray-500">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3">Name</th>
          <th scope="col" class="px-6 py-3">Email</th>
          <th scope="col" class="px-6 py-3">Status</th>
          <th scope="col" class="px-6 py-3">Role</th>
          <th scope="col" class="px-6 py-3">Added at</th>
          <th scope="col" class="px-6 py-3"></th>
        </tr>
      </thead>
      <tbody>

      </tbody>
    </table>
    <%= link_to "Add User", new_account_user_path, class: "inline-flex mt-4 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>
  </div>
</div>

app/views/users/me.html.erb
<div class="flex p-5" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-3">
    <li class="inline-flex items-center">
      <h2 href="#" class="inline-flex items-center font-medium text-gray-700 hover:text-gray-900">
        Users
      </h2>
    </li>
    <li class="inline-flex items-center">
      <h2 href="#" class="inline-flex items-center font-medium text-gray-700 hover:text-gray-900">
        <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
        </svg>
        My Settings
      </h2>
    </li>
  </ol>
</div>

<div class="flex justify-center">
  <div class="p-4 w-4/5 bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 lg:p-8">
    <h5 class="text-xl font-bold leading-none text-gray-900">Edit My Information:</h5>
    <%= form_with(model: @user, url: update_my_settings_path, id: 'edit_my_user', html: {class: 'space-y-6'}) do |f| %>
      <% if @user.errors.any? %>
        <div class="text-red-700">
          <h4>
            <%= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:" %>
          </h4>
          <%== @user.errors.full_messages.map{|msg|content_tag(:li, msg)}.join %>
        </div>
      <% end %>

      <div>
        <%= f.label :name, class: 'block mb-2 text-sm font-medium text-gray-900' %>
        <%= f.text_field :name, placeholder: 'Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
      </div>

      <div>
        <%= f.label :email, class: 'block mb-2 text-sm font-medium text-gray-900' %>
        <%= f.email_field :email, placeholder: 'Enter their email address', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
      </div>

      <div>
        <%= f.label :time_zone, class: 'block mb-2 text-sm font-medium text-gray-900' %>
        <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {}, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
      </div>

      <%= f.submit "Update My Settings", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="flex p-5" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-3">
    <li class="inline-flex items-center">
      <h2 href="#" class="inline-flex items-center font-medium text-gray-700 hover:text-gray-900">Users</h2>
    </li>
    <li class="inline-flex items-center">
      <h2 href="#" class="inline-flex items-center font-medium text-gray-700 hover:text-gray-900">
        <a href="http://localhost:3000/account/users" class="inline-flex items-center">
          Users are Everything 117
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
          </svg>
          New
        </a>
      </h2>
    </li>
  </ol>
</div>

<div class="flex justify-center">
  <div class="p-4 w-4/5 bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 lg:p-8">
    <h5 class="text-xl font-bold leading-none text-gray-900">Add a new user:</h5>
    <%= form_with(model: @user, url: account_users_path, id: 'new_user', html: {class: 'space-y-6'}) do |f| %>
      <% if @user.errors.any? %>
        <div class="text-red-700">
          <h4><%= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:" %></h4>
          <%== @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join %>
        </div>
      <% end %>

      <div>
        <%= f.label :name, class: 'block mb-2 text-sm font-medium text-gray-900' %>
        <%= f.text_field :name, placeholder: 'Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
      </div>

      <div>
        <%= f.label :email, class: 'block mb-2 text-sm font-medium text-gray-900' %>
        <%= f.email_field :email, placeholder: 'Enter their email address', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
      </div>

      <div>
        <%= f.label :role, class: 'block mb-2 text-sm font-medium text-gray-900' %>
        <%= f.select :role, options_for_select(@choices, 'user'), {}, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
      </div>

      <%= f.submit "Add User", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>
    <% end %>
  </div>
</div>

app/views/users/password.html.erb
<div class="flex p-5" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-3">
    <li class="inline-flex items-center">
      <h2 href="#" class="inline-flex items-center font-medium text-gray-700 hover:text-gray-900">
        Users
      </h2>
    </li>
    <li class="inline-flex items-center">
      <h2 href="#" class="inline-flex items-center font-medium text-gray-700 hover:text-gray-900">
        <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
        </svg>
        My Password
      </h2>
    </li>
  </ol>
</div>

<div class="flex justify-center">
  <div class="p-4 w-4/5 bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 lg:p-8">
    <h5 class="text-xl font-bold leading-none text-gray-900">Update My Information:</h5>
    <%= form_with(model: @user, url: my_update_password_path, id: 'edit_my_password', html: {class: 'space-y-6'}) do |f| %>
      <% if @user.errors.any? %>
        <div class="text-red-700">
          <h4>
            <%= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:" %>
          </h4>
          <%== @user.errors.full_messages.map{|msg|content_tag(:li, msg)}.join %>
        </div>
      <% end %>

      <div>
        <%= f.label :password, class: 'block mb-2 text-sm font-medium text-gray-900' %>
        <%= f.password_field :password, placeholder: 'New Password', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
      </div>

      <div>
        <%= f.label :password_confirmation, class: 'block mb-2 text-sm font-medium text-gray-900' %>
        <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5' %>
      </div>

      <%= f.submit "Update Password", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <h1 class="font-bold text-4xl">User#show</h1>
  <p>Find me in app/views/user/show.html.erb</p>
</div>

app/views/users/update.html.erb
<div>
  <h1 class="font-bold text-4xl">User#update</h1>
  <p>Find me in app/views/user/update.html.erb</p>
</div>